# Example GitLab CI jobs for running release.sh non-interactively.
#
# Trigger the release job manually from the GitLab UI by setting RELEASE_VERSION
# (e.g. "1.2.3"). The job will create a release branch and tag.
#
# Trigger the hotfix-mr job by setting HOTFIX_BRANCH (e.g. "release/v1.2.3").
# The job will create a merge request from the release branch back to the
# default branch.

release:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_DEPTH: 0  # Full history needed for changelog generation
  before_script:
    - apk add --no-cache bash git curl jq
    # Ensure full history even if GIT_DEPTH was ignored
    - git fetch --unshallow 2>/dev/null || true
    - git fetch --tags
    # Configure git user for annotated tags
    - git config user.name "GitLab CI"
    - git config user.email "ci@${CI_SERVER_HOST}"
  script:
    - ./scripts/release.sh --version "$RELEASE_VERSION" --non-interactive
  rules:
    - if: '$RELEASE_VERSION'
      when: manual
  allow_failure: false

hotfix-mr:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_DEPTH: 0
  before_script:
    - apk add --no-cache bash git curl jq
    - git fetch --unshallow 2>/dev/null || true
    - git fetch --tags
  script:
    - ./scripts/release.sh --hotfix-mr "$HOTFIX_BRANCH" --non-interactive
  rules:
    - if: '$HOTFIX_BRANCH'
      when: manual
  allow_failure: false
